# Aquameta Configuration



# PostgreSQL connection settings
[Database]
User = "eric"
Password = "whatevz"
Host = "localhost"
Port = 9876
DatabaseName = "aquameta"
RuntimePath = "./postgres"

[User]
Name = "Hanson"
Email = "eric@aquameta.com"

[Webserver]
#  Web server settings
IP = "127.0.0.1"
Port = "4444"
Protocol = "http" # http or https
SSLCertificateFile = "certificates/server.crt"
SSLKeyFile = "certificates/server.key"

[Webrtc]
