# Aquameta Configuration

[Database]
    Mode = "embedded"               # { embedded | standalone } - if embedded, aquameta will create a new PostgreSQL
                                    # server instance. If "standalone", use an existing server managed by Aquameta.

    # the path where the embedded postgresql instance will be installed (if applicable)
    EmbeddedPostgresRuntimePath = "./bootloader.db"

    # connection settings
    Host = "127.0.0.1"                        # host
    Port = 9876                     # instance will open (sometimes 5432)
    DatabaseName = "bootloader"       # name of the database to be created where Aquameta will be installed

    # authentication settings
    Role = "bootloader"
    Password = "bootloader"            # FIXME - we probably want to use peer auth over unix sockets instead if possible?


[AquametaUser]                      # Record to create in `endpoint.user` table
    Name = "Bootloader User"
    Email = ""



[HTTPServer]
    Protocol = "http"               # { http | https }
    IP = "127.0.0.1"                # IP to bind to
    Port = "4444"                   # Port to open

    # only used w/ https
    SSLCertificateFile = "certificates/server.crt"
    SSLKeyFile = "certificates/server.key"


